name:                halg
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/halg#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Unclassified
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - array >= 0.5

executables:
  halg:
    source-dirs:      src
    main:             Main.hs
